"""initial migration

Revision ID: cbad5199a3d0
Revises:
Create Date: 2025-01-15 12:59:58.566732

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cbad5199a3d0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
